permalink: /:categories/:title/
url: "http://example.com"
full_name: "Saigon Jekyll Theme"
first_name: "Rebecca"
last_name: "Me"
blog_title: "Brave New World"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2018"
google_analytics_code: ""
aboutme: "I like bad ramen noodles"
