permalink: /:categories/:title/
url: "https://luure835.github.io/"
full_name: "Rebecca"
first_name: "Rebecca"
last_name: "L"
blog_title: "Brave New World"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2018"
google_analytics_code: ""
aboutme: "I like bad ramen noodles"
